[build]
builder = "nixpacks"

[deploy]
numReplicas = 1

[env]
DB_PATH = "/data/db.sqlite3"
MEDIA_ROOT = "/data/media"
DEBUG = "True"
SECRET_KEY = "&)+-e=tus4kizmhn&8lez-lr761nsb^6x0o$igi20zq=##$(zc"

[[volumes]]
mountPath = "/data"
name = "storage"
