# Generated by Django 5.2.7 on 2025-11-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='receiver',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
