# Generated by Django 5.2.7 on 2026-03-06 19:13

from django.db import migrations


def populate_categories_and_shares(apps, schema_editor):
    """Create Category objects from existing text categories and link expenses."""
    Expense = apps.get_model('expenses', 'Expense')
    Category = apps.get_model('expenses', 'Category')
    
    # Get all unique categories from existing expenses
    unique_categories = Expense.objects.values_list('category', flat=True).distinct()
    
    # Create categories for each unique value
    for cat_name in unique_categories:
        if cat_name:  # Skip empty/null values
            Category.objects.get_or_create(name=cat_name, defaults={'is_system': False})
    
    # Link each expense to its category object and set user_share
    for expense in Expense.objects.all():
        if expense.category:
            try:
                category_obj = Category.objects.get(name=expense.category)
                expense.category_obj = category_obj
            except Category.DoesNotExist:
                pass
        
        # Set user_share to full amount (no splits initially)
        if expense.user_share is None:
            expense.user_share = expense.amount
        
        expense.save(update_fields=['category_obj', 'user_share'])


def reverse_populate(apps, schema_editor):
    """Reverse: clear category_obj and user_share."""
    Expense = apps.get_model('expenses', 'Expense')
    Expense.objects.all().update(category_obj=None, user_share=None)


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_user_share_category_expense_category_obj_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_categories_and_shares, reverse_populate),
    ]
