# Generated by Django 5.2.7 on 2026-03-06 19:33

from django.db import migrations


def link_categories_to_users(apps, schema_editor):
    """Link imported categories to users who own the expenses."""
    Expense = apps.get_model('expenses', 'Expense')
    Category = apps.get_model('expenses', 'Category')
    
    # For each non-system category
    for category in Category.objects.filter(is_system=False):
        # Find any expense with this category
        expense_with_category = (
            Expense.objects.filter(category_obj=category)
            .values_list('user', flat=True)
            .first()
        )
        
        if expense_with_category:
            # Link category to that user
            category.user_id = expense_with_category
            category.save(update_fields=['user'])


def reverse_link(apps, schema_editor):
    """Reverse: set user back to NULL for imported categories."""
    Category = apps.get_model('expenses', 'Category')
    Category.objects.filter(is_system=False).update(user=None)


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_populate_categories_and_shares'),
    ]

    operations = [
        migrations.RunPython(link_categories_to_users, reverse_link),
    ]
