# Generated by Django 5.2.7 on 2026-03-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_link_categories_to_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keywords',
            field=models.TextField(blank=True, help_text="Comma-separated keywords for auto-matching expenses (e.g., 'lidl,prisma,k-market')"),
        ),
    ]
