# Generated by Django 5.2.7 on 2026-03-06 19:48

from django.db import migrations


def update_keywords(apps, schema_editor):
    Category = apps.get_model('expenses', 'Category')
    
    keywords_map = {
        'Groceries': 'lidl,prisma,k-supermarket,k-market,market,carrefour,supermarket,food,grocery,deli,ruoka,kauppa',
        'Transport': 'taxi,uber,matka,bus,juna,vr,train,lentokentta,airport,kuljetus,statoil,neste,shell,bp,bensiini,polttoaine,pumppu,kaasu,psi',
        'Entertainment': 'netflix,spotify,disney,hbo,cinema,theatre,youtube,entertainment,movies,elokuva,teatteri',
        'Utilities': 'sähkö,electricity,vesi,water,internet,puhelin,phone,energia,energy,liittymä',
        'Healthcare': 'apteekki,pharmacy,health,doctor,dentist,hospital,clinic,lääkäri,hammaslääkäri',
        'Shopping': 'shop,store,h&m,zara,mango,amazon,verkkokauppa,myymälä,kauppa,vaatteet',
        'Dining': 'restaurant,cafe,kebab,pizza,burger,mcdonalds,taco,drink,bar,pub,ravintola,ruokala',
        'Other': 'misc,muuta,other',
    }
    
    for category_name, keywords in keywords_map.items():
        Category.objects.filter(name=category_name, is_system=True).update(keywords=keywords)


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_category_keywords'),
    ]

    operations = [
        migrations.RunPython(update_keywords),
    ]
