# Generated by Django 5.2.7 on 2026-03-06 20:29

from django.db import migrations, models


def add_savings_and_transfer_categories(apps, schema_editor):
    Category = apps.get_model("expenses", "Category")

    # Ensure default system categories exist for this new behavior.
    Category.objects.get_or_create(
        user=None,
        name="Savings",
        defaults={
            "is_system": True,
            "keywords": "savings,save,investment,fund,rahasto,säästö,deposit",
            "category_type": "saving",
        },
    )
    Category.objects.get_or_create(
        user=None,
        name="Transfers",
        defaults={
            "is_system": True,
            "keywords": "transfer,tilisiirto,siirto,internal transfer,own account",
            "category_type": "transfer",
        },
    )

    # If similar categories already exist, classify them so they don't count as spending.
    Category.objects.filter(name__iexact="savings").update(category_type="saving")
    Category.objects.filter(name__iexact="saving").update(category_type="saving")
    Category.objects.filter(name__iexact="transfers").update(category_type="transfer")
    Category.objects.filter(name__iexact="transfer").update(category_type="transfer")


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_update_category_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('expense', 'Expense'), ('saving', 'Saving'), ('transfer', 'Transfer')], default='expense', max_length=20),
        ),
        migrations.RunPython(add_savings_and_transfer_categories, migrations.RunPython.noop),
    ]
