# Generated by Django 5.2.7 on 2026-03-20 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_user_owned_default_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.category')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='expenses.expense')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
    ]
