# Generated by Django 5.2.7 on 2026-04-08 17:04

from django.db import migrations


def create_spiir_categories(apps, schema_editor):
    """Create Spiir default categories as system templates."""
    Category = apps.get_model('expenses', 'Category')
    
    # Category data: (name, category_type, keywords, parent_name_or_none)
    categories_data = [
        # Root categories (MainCategories)
        ('Auto & Transport', 'expense', '', None),
        ('Basic Expenses', 'expense', '', None),
        ('Debt & Interest', 'expense', '', None),
        ('Home', 'expense', '', None),
        ('Household', 'expense', '', None),
        ('Income', 'income', '', None),
        ('Leisure', 'expense', '', None),
        ('Other', 'expense', '', None),
        ('Pension & Savings', 'saving', '', None),
        ('Transfers', 'transfer', 'transfer,internal transfer,own account', None),
        ('Travel', 'expense', '', None),
        
        # Auto & Transport subcategories
        ('Auto Insurance & Assistance', 'expense', 'insurance,auto', 'Auto & Transport'),
        ('Auto Loan etc.', 'expense', 'loan,auto', 'Auto & Transport'),
        ('Fuel', 'expense', 'fuel,petrol,diesel,gas,shell,neste,circlek', 'Auto & Transport'),
        ('Garage & Auto Parts', 'expense', 'garage,auto,parts,mechanic,repair', 'Auto & Transport'),
        ('Other Transport', 'expense', 'transport', 'Auto & Transport'),
        ('Parking', 'expense', 'parking', 'Auto & Transport'),
        ('Public Transport', 'expense', 'bus,train,metro,tram,ticket', 'Auto & Transport'),
        ('Road Tax & Green Tax', 'expense', 'tax,road', 'Auto & Transport'),
        ('Taxi', 'expense', 'taxi,uber,lyft', 'Auto & Transport'),
        
        # Basic Expenses subcategories
        ('Glasses & Contacts', 'expense', 'glasses,contacts,optician,vision', 'Basic Expenses'),
        ('Health Insurance', 'expense', 'health,insurance', 'Basic Expenses'),
        ('Life & Accident Insurance', 'expense', 'life,accident,insurance', 'Basic Expenses'),
        ('Medical Specialists', 'expense', 'doctor,specialist,medical,clinic', 'Basic Expenses'),
        ('Pharmacy', 'expense', 'pharmacy,medicine,drug,prescription', 'Basic Expenses'),
        ('Phone & Internet', 'expense', 'phone,internet,mobile,provider,telia,sonera,elisa,dna', 'Basic Expenses'),
        ('TV & Streaming', 'expense', 'tv,streaming,netflix,hbo,spotify,discovery', 'Basic Expenses'),
        ('Union & Unemployment Insurance', 'expense', 'union,unemployment,insurance', 'Basic Expenses'),
        
        # Debt & Interest subcategories
        ('Consumer Loan', 'expense', 'consumer,loan', 'Debt & Interest'),
        ('Interest', 'expense', 'interest', 'Debt & Interest'),
        ('Private Loan (Friends & Family)', 'expense', 'private,loan,friend,family', 'Debt & Interest'),
        
        # Home subcategories
        ('Building Insurance', 'expense', 'building,insurance,home', 'Home'),
        ('Contents Insurance', 'expense', 'contents,insurance,household', 'Home'),
        ('Garden & Plants', 'expense', 'garden,plants,flowers,seeds', 'Home'),
        ('Mortgage/Rent', 'expense', 'mortgage,rent,landlord', 'Home'),
        ('Other Housing Expenses', 'expense', 'housing,expenses', 'Home'),
        ('Property Tax', 'expense', 'property,tax', 'Home'),
        ('Remodeling & Repair', 'expense', 'remodel,repair,renovation,construction', 'Home'),
        ('Utilities', 'expense', 'utilities,electricity,water,heating,power,fortum,helen', 'Home'),
        
        # Household subcategories
        ('Meal Plan', 'expense', 'meal,plan,lunch,lunch card', 'Household'),
        ('Mini-markets & Delicacies', 'expense', 'mini,market,delicacies', 'Household'),
        ('Supermarket', 'expense', 'supermarket,market,prisma,lidl,k-market,s-market,abc,citymarket', 'Household'),
        
        # Income subcategories
        ('Interest Income', 'income', 'interest,income', 'Income'),
        ('Other Income', 'income', 'income', 'Income'),
        ('Overpaid Tax', 'income', 'tax,overpaid', 'Income'),
        ('Salary', 'income', 'salary,wage,paycheck,payment', 'Income'),
        
        # Leisure subcategories
        ('Betting', 'expense', 'betting,gamble,lottery', 'Leisure'),
        ('Cinema, Concerts & Entertainment', 'expense', 'cinema,concert,entertainment,movie,theatre', 'Leisure'),
        ('Clothing & Accessories', 'expense', 'clothing,clothes,fashion,dress,shoes,coat', 'Leisure'),
        ('Electronics & Computer', 'expense', 'electronics,computer,tech,gadget', 'Leisure'),
        ('Fast Food & Takeaway', 'expense', 'fast food,takeaway,mcdonald,burger,pizza,subway,kebab', 'Leisure'),
        ('Furniture & Interior', 'expense', 'furniture,interior,home,decor', 'Leisure'),
        ('Games & Toys', 'expense', 'games,toys,gaming', 'Leisure'),
        ('Gifts & Charity', 'expense', 'gifts,charity,donation,present', 'Leisure'),
        ('Hairdresser & Personal Care', 'expense', 'hairdresser,haircut,salon,personal,care,barber', 'Leisure'),
        ('Hobby & Sports Equipment', 'expense', 'hobby,sports,equipment,gym', 'Leisure'),
        ('Housekeeping & Gardening', 'expense', 'housekeeping,cleaning,garden', 'Leisure'),
        ('Movies, Music & Books', 'expense', 'movies,music,books,library', 'Leisure'),
        ('Online Services & Software', 'expense', 'online,services,software,subscription,app', 'Leisure'),
        ('Other Private Consumption', 'expense', 'consumption,personal', 'Leisure'),
        ('Pets', 'expense', 'pets,dog,cat,animal,vet', 'Leisure'),
        ('Restaurants & Bars', 'expense', 'restaurant,bar,cafe,coffee,dining,espresso,pizza,sushi,asian', 'Leisure'),
        ('Sports & Leisure', 'expense', 'sports,leisure,recreational', 'Leisure'),
        ('Tobacco & Alcohol', 'expense', 'tobacco,alcohol,beer,wine,spirits,cigarette', 'Leisure'),
        
        # Other subcategories
        ('Bank Fees', 'expense', 'bank,fees,charge', 'Other'),
        ('Fines', 'expense', 'fines,fine,penalty', 'Other'),
        ('Public fee', 'expense', 'public,fee', 'Other'),
        ('Unknown', 'expense', '', 'Other'),
        ('Unpaid Tax', 'expense', 'tax,unpaid', 'Other'),
        
        # Pension & Savings subcategories
        ('Other Savings', 'saving', 'savings', 'Pension & Savings'),
        ('Pension Savings', 'saving', 'pension,savings', 'Pension & Savings'),
        ('Stock Trading', 'saving', 'stock,trading,investment', 'Pension & Savings'),
        
        # Travel subcategories
        ('Flights & Hotels', 'expense', 'flights,hotels,flight,hotel,airbnb', 'Travel'),
        ('Vacation Activities', 'expense', 'vacation,activity,excursion', 'Travel'),
    ]
    
    # Skip if categories already exist
    if Category.objects.filter(is_system=True, user__isnull=True).exists():
        return
    
    # First pass: create root categories
    root_objects = []
    for name, cat_type, keywords, parent_name in categories_data:
        if parent_name is None:
            root_objects.append(
                Category(
                    name=name,
                    category_type=cat_type,
                    keywords=keywords,
                    is_system=True,
                    user=None,
                )
            )
    Category.objects.bulk_create(root_objects, ignore_conflicts=True)
    
    # Fetch created roots for second pass
    root_categories = {
        cat.name: cat for cat in Category.objects.filter(
            is_system=True, user__isnull=True, parent__isnull=True
        )
    }
    
    # Second pass: create subcategories
    sub_objects = []
    for name, cat_type, keywords, parent_name in categories_data:
        if parent_name is not None and parent_name in root_categories:
            sub_objects.append(
                Category(
                    name=name,
                    category_type=cat_type,
                    keywords=keywords,
                    is_system=True,
                    user=None,
                    parent=root_categories[parent_name],
                )
            )
    Category.objects.bulk_create(sub_objects, ignore_conflicts=True)

    # Seed new system categories to all existing users
    User = apps.get_model('auth', 'User')
    templates = list(
        Category.objects.filter(is_system=True, user__isnull=True)
        .select_related('parent')
        .order_by('parent_id')
    )

    for user in User.objects.all():
        seeded = {}
        for template in templates:
            parent = seeded.get(template.parent_id) if template.parent_id else None
            defaults = {
                'category_type': template.category_type,
                'keywords': template.keywords,
                'is_system': False,
            }
            if parent:
                defaults['parent'] = parent

            cat, _ = Category.objects.get_or_create(
                user=user,
                name=template.name,
                defaults=defaults,
            )
            seeded[template.pk] = cat


def reverse_spiir_categories(apps, schema_editor):
    """Remove Spiir categories created by this migration.

    The forward function is a noop when system categories already exist (seeded
    by migration 0008).  We detect that case by looking for the "Savings"
    category which is unique to 0008 (the Spiir list uses different names).

    When the forward DID create categories, we use raw SQL to delete them so
    that Django's cascade collector does not try to query tables (e.g.
    expenses_expensepart) that may not exist when reversing through earlier
    migrations.
    """
    Category = apps.get_model('expenses', 'Category')
    if Category.objects.filter(
        is_system=True, user__isnull=True, name="Savings"
    ).exists():
        return
    schema_editor.execute(
        "DELETE FROM expenses_category WHERE is_system AND user_id IS NULL"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_convert_parts_remove_expensepart'),
    ]

    operations = [
        migrations.RunPython(create_spiir_categories, reverse_spiir_categories),
    ]
